export const SECTORS = [
  'Real Estate & Construction',
  'Healthcare & Medical',
  'Technology & Software',
  'Manufacturing & Industrial',
  'Retail & E-commerce',
  'Food & Beverage',
  'Education & Training',
  'Tourism & Hospitality',
  'Agriculture & Farming',
  'Energy & Utilities',
  'Transportation & Logistics',
  'Financial Services',
  'Media & Entertainment',
  'Professional Services',
  'Other',
] as const;

export const COUNTRIES = [
  'Saudi Arabia',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Egypt',
  'Jordan',
  'Lebanon',
  'Morocco',
  'Tunisia',
  'Algeria',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Canada',
  'Australia',
  'India',
  'China',
  'Japan',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Turkey',
  'Pakistan',
  'Bangladesh',
  'Other',
] as const;

export const REPORT_SECTIONS = [
  'Executive Summary',
  'Project Overview',
  'Market Analysis',
  'Technical Feasibility',
  'Financial Analysis',
  'Risk Assessment',
  'Implementation Plan',
  'Recommendations',
  'Appendices',
] as const;

export const PROJECT_STATUS = {
  DRAFT: 'draft',
  GENERATING: 'generating',
  COMPLETED: 'completed',
  FAILED: 'failed',
} as const;
